In [1]:
import numpy as np

In [12]:
l1 = [0,1,2,3,4]
l2 = np.array(l1)
print(l1)
print(type(l1))
print(l2)
print(type(l2))

[0, 1, 2, 3, 4]
<class 'list'>
[0 1 2 3 4]
<class 'numpy.ndarray'>


In [13]:
l2.resize((3,2))
print(l2)
print(l2.shape)

[[0 1]
 [2 3]
 [4 0]]
(3, 2)


In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
l2.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 0]])

In [19]:
print(l2)

[[0 1]
 [2 3]
 [4 0]]


In [20]:
l2.resize((3,2))
print(l2)

[[0 1]
 [2 3]
 [4 0]]


In [21]:
l4 = np.arange(24).reshape((4,6))
print(l4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [22]:
l5 = l4[1:4,-3:]
print(l5)

[[ 9 10 11]
 [15 16 17]
 [21 22 23]]
